name: Trigger on Pull Requests

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:      
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Install Pytest
      run: |
        python -m pip install -r requirements.txt  
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Run Pytests
      run: | 
        pytest tests/    
