name: Trigger on Pull Requests

on:
  pull_request_target:
    branches:
      - main

jobs:
  pull_request_checking:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Install Pytest
      run: |
        python -m pip install -r requirements.txt  
    - name : machine ls $GITHUB_WORKSPACE
      run : "ls -la $GITHUB_WORKSPACE"  
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Run Pytests
      run: | 
        pytest tests/    

