name: Trigger on Pull Requests

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:      
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"
